### ISSUE TITLE
Replace "debug" with "log" constructor option

### ISSUE THREAD

**Issue by dominguezcelada** [octokit/webhooks#140]
We don't use the `debug` package in any other Octokit module. Instead we use a `console`-compatible `log` API, and users can pass their own `log` object, see https://github.com/octokit/core.js#logging

More info here: https://github.com/octokit/webhooks.js/issues/186

**Comment by gr2m** [comment]
Actually I don't mind using `debug` in this repository, because it's not a library that is used at runtime, but a CLI tool that creates static artifacts. `debug` is great for that, because it's fully controllable using envriontment variables. If a build in CI fails, we can change the `debug` environment variable and re-run the same build
