### ISSUE TITLE
Programatically PR new common Schemas

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks#313]
Still have to take a look into @G-Rath scripts but, would have sense to run those scripts programmatically and open a PR for each common schema change proposal instead of spotting them during our developments?

Has sense what I'm asking? Would it be feasible? @G-Rath @wolfy1339

---

Are you proposing creating a new `common` schema?

That's fine with me - I've got two scripts for doing that: `extract-common-schema` & `ref-common-schemas`.

The first takes a path to a property on an interface and the name you want to give the interface for that common interface, and figures out how to extract the schema.

The second then goes through all the schemas and compared each property + value to all our common schemas, replacing any that match with references to the matching schema.

So in this case, you'd run `bin/extract-common-schema IssueCommentCreated.issue issue` to extract the schema, and then `bin/ref-common-schemas` to replace all objects that match the newly created schema with a reference :)

There are *tons* of common schemas to be extracted - pretty much every event has at least one common schema, since we're got a schema per action (i.e "issue" events will have an issue property, pull_request events all have a `pull_request` property, milestones all have a `milestone` property, etc) so feel free to go nuts!

_Originally posted by @G-Rath in https://github.com/octokit/webhooks/issues/312#issuecomment-763487830_

**Comment by G-Rath** [comment]
I don't think it will be feasible - there are a lot of different common schemas you could make, and some make more sense then others due to property differences

i.e `label` exists both as an object that requires all properties and as all properties being partial. You'd need to put about the same amount of work reviewing the programmatically generated PRs both individually and as a group as you would identifying good common schemas manually.

Meanwhile IntelliJ supports identifying duplicate code, so I can easily have it tell me when something would make a good common schema :)

**Comment by wolfy1339** [comment]
Closing since as per previous comment
