### ISSUE TITLE
To check "Dismiss stale pull request approvals when new commits are pushed"

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks#318]
**What’s missing?**
To check "Dismiss stale pull request approvals when new commits are pushed" (https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule#creating-a-branch-protection-rule)

**Why?**
To require review of a PR if it has changed since last approval. 
**Example:** https://github.com/octokit/webhooks/pull/317

**Comment by G-Rath** [comment]
Do we have to have this? I understand the advantages, but it comes at the disadvantage of potentially slowing things down i.e if I have a PR open that I'm about to merge, but something else gets merged that requires me to rebase, I now have to get a reapproval even if nothing's changed (say because if it was a `package-lock.json` "conflict").

We can dismiss peoples reviews, which'll block PRs from getting merged, and we do automatic releases so rolling back a change is easy - I'm not strongly against having this on, but just wondering if it's going to solve any problems that makes it worth the extra overhead.

**Comment by oscard0m** [comment]
> Do we have to have this? I understand the advantages, but it comes at the disadvantage of potentially slowing things down i.e if I have a PR open that I'm about to merge, but something else gets merged that requires me to rebase, I now have to get a reapproval even if nothing's changed (say because if it was a `package-lock.json` "conflict").
> 
> We can dismiss peoples reviews, which'll block PRs from getting merged, and we do automatic releases so rolling back a change is easy - I'm not strongly against having this on, but just wondering if it's going to solve any problems that makes it worth the extra overhead.

I see your point. For sure it's super pleasant to merge and release code super fast. It's super grateful.

I just wanted to prevent merging code which should be human-reviewed and CI checks are not able to spot (architecture or potential breaking changes introduced). Since we work with releases I think it's important to not mess up with users.

Maybe we can rely on contributor's responsibility of asking for second opinions if there are doubts (even the PR is mergeable?) and keep it as it is?

**Comment by G-Rath** [comment]
> Maybe we can rely on contributor's responsibility of asking for second opinions if there are doubts (even the PR is mergeable?) and keep it as it is?

That sounds like a good way to go to me :)
