### ISSUE TITLE
Schemas should be using `draft-2019-09` due to using other keywords along with `$ref`

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks#481]
**What happened?**

Revisiting #420 and looking at the spec, I realized that theoretically we shouldn't have other keywords along with `$ref`.

**What did you expect to happen?**

For the schemas to respect the spec

**What the problem might be**

Use the `draft/2019-09` spec instead of `draft-07`

The differences between the versions can be found here: https://json-schema.org/draft/2019-09/release-notes.html

**Note:** Support for `2019-09` in VSCode isn't complete, so it will complain, however, we don't use any of the newer features.

**Comment by oscard0m** [comment]
What's the impact or potential impact of using different version? Queries failing for example?

**Comment by G-Rath** [comment]
That's not actually a problem - the schema says that when validators deal with `$ref`:

> All other properties in a "$ref" object MUST
   be ignored.

This means that our schemas are valid and conform to the spec since we're not using the properties along side `$ref` for validation - were using them as a form of metadata for other tools that consume the schemas to generate other files (i.e. types)

I really dont want to move to the latest schema becuase there is very little support for it yet: both VSCode and IntelliJ don't support it, and ajv has only just landed support.

**Comment by G-Rath** [comment]
@wolfy1339 are you happy to close this since it's not an issue?
