### ISSUE TITLE
Document how we get from a new webhook event to a new schema and to new types

### ISSUE THREAD

**Issue by gr2m** [octokit/webhooks#643]
Follow up to https://github.com/octokit/webhooks/pull/641#discussion_r898325831

**Comment by wolfy1339** [comment]
Here's a rough idea of how to make schemas

## Creating a new schema

Schemas are manually created using example payloads for webhook events.
- Create a new folder for the event in `payload-schemas/api.github.com`, if it doesn't already exist
- Create a new empty JSON file named `<action>.schema.json` if the event has an `action` property, otherwise name it `event.schema.json`
- Set the `$schema` property to `"http://json-schema.org/draft-07/schema"`
- The `$id` property's value should be in the format `<eventName>$action`, where `<eventName>` is the name of the event, and `action` is the value of the `action` property of the webhook payload or simply `event` if there is no `action` property for the event
- the `title` property's value should be in the format `<eventName> <action> event`, where `<eventName>` is the name of the event, and `<action>` is the value of the `action` property of the webhook payload. If there is no action, the it should simply be `<eventName> event`
- `type` should be `object`
- Add any required properties in an array in the `required` property
- Define properties of the payload in the [`properties` property](http://json-schema.org/understanding-json-schema/reference/object.html#properties) as an object in that property, like so:
```json
{
   "properties": {
      "myproperty": {
         "type": "int",
         "description": "My Property's description"
      }
   }
}
```
   - When a property is a `string`, or `number` and has a defined set of values it can be, add the values in an array in the `enum` property of the property's object
   - When a property can be of multiple types, use a [`oneOf`](http://json-schema.org/understanding-json-schema/reference/combining.html#oneof) for the decleration of that property, and declare each type in the `oneOf`
   - When a property can be not present:
      - if there is only one other type the property can be, change the `type` property to an array including the type, and the string `null`
      - if there are more than one other type, that the property can be, simply add it to the `oneOf`
   - Repeat until you reach the lowest level of the payload
- Add `"additionalProperties": false` to each property of the payload, and to the root of the document as well

**Comment by gr2m** [comment]
This is great! Would you like to send a pull request for the contributing file?
